=begin

File name: mapHelper.rb
Description: This class scrap essential informations to help generating Google Map (hardcode.txt)

Main functionality: Scrap program name and cities
                    Print result For hardcoding (used in google map)

Log:06/13 Implemented by Yi. 
=end

require 'json'
require 'mechanize'
require_relative '../LocationSet.rb'
require_relative 'Geomap.rb'

class MapHelper
    # Get Json
    json_from_file = File.read("./geocode.json")
    geo = JSON.parse(json_from_file)
    geoarr = []


    arr = [["AIFS Study Abroad in London: Semester Internship","London"],
    ["AIFS Study Abroad in London: Semester or Academic Year","London"],
    ["AIFS Study Abroad in London: Summer","London"],
    ["AIFS Study Abroad in London: Summer Globe Education Theater Program","London"],
    ["AIFS Study Abroad in London: Summer Internship","Prague"],
    ["AIFS Study Abroad in Prague, Charles University: Semester or Academic Year","Prague"],
    ["AIFS Study Abroad in Prague: Summer","Rome"],
    ["AIFS Study Abroad in Rome: Semester Internship","Salzburg"],
    ["AIFS Study Abroad in Salzburg: Semester or Academic Year","Salzburg"],
    ["AIFS Study Abroad in Salzburg: Summer","Stellenbosch"],
    ["AIFS Study Abroad in Stellenbosch: Semester or Academic Year","Stellenbosch"],
    ["AIFS Study Abroad in Stellenbosch: Service Learning Semester or Year","Stellenbosch"],
    ["AIFS Study Abroad in Stellenbosch: Summer","Stellenbosch"],
    ["AIFS Study Abroad in Stellenbosch: Summer Service Learning","Moscow"],
    ["American Councils: RLASP – Advanced Russian Language & Area Studies Program","Amman"],
    ["AMIDEAST Area & Arabic Language Studies in Jordan (Semester/Academic Year)","Amman"],
    ["AMIDEAST Intensive Arabic in Amman, Jordan (Summer)","Cochabamba"],
    ["Amizade Global Service-Learning For STEP Students, Bolivia","Petersfield"],
    ["Arcadia in Dublin Summer","Dublin"],
    ["Arcadia in Greece","Athens"],
    ["Arcadia in London","London"],
    ["Arcadia in London Summer","London"],
    ["Arcadia in Rome","Rome"],
    ["Arcadia University - Accademia Italiana Florence","Florence"],
    ["Arcadia University - Arcadia in Sydney Summer","Sydney"],
    ["Arcadia University - Athens Internship Program","Athens"],
    ["Arcadia University - Australian National University","Canberra"],
    ["Arcadia University - Bangor University","Bangor"],
    ["Arcadia University - Burren College of Art","Ballyvaughan"],
    ["Arcadia University - City University London","London"],
    ["Arcadia University - Dublin Internship Program Summer","Dublin"],
    ["Arcadia University - Dublin Parliamentary Internship","Dublin"],
    ["Arcadia University - Edinburgh Napier University","Edinburgh"],
    ["Arcadia University - Environmental Studies: Ethics, Culture, and Sustainability","Christchurch"],
    ["Arcadia University - Food & Sustainability Studies, Perugia","Perugia"],
    ["Arcadia University - Glasgow School of Art","Glasgow"],
    ["Arcadia University - Goldsmiths, University of London","London"],
    ["Arcadia University - Griffith University","Brisbane"],
    ["Arcadia University - Intensive Design in Florence","Florence"],
    ["Arcadia University - Italian Language and Culture in Florence","Florence"],
    ["Arcadia University - James Cook University","Townsville"],
    ["Arcadia University - King's College London","London"],
    ["Arcadia University - Kings College London Health and Society","London"],
    ["Arcadia University - London Internship Program","London"],
    ["Arcadia University - London Internship Program Summer","London"],
    ["Arcadia University - London School of Economics","London"],
    ["Arcadia University - Macquarie University","Sydney"],
    ["Arcadia University - Maynooth University","Maynooth"],
    ["Arcadia University - Museum Studies Internship Program","Edinburgh"],
    ["Arcadia University - National University of Ireland Galway","Galway"],
    ["Arcadia University - Pembroke-King's at University of Cambridge","Cambridge"],
    ["Arcadia University - Queen Mary University of London","London"],
    ["Arcadia University - Queens University Belfast","Belfast"],
    ["Arcadia University - Queensland University of Technology","Brisbane"],
    ["Arcadia University - Rome Internship Program","Rome"],
    ["Arcadia University - Royal Conservatoire of Scotland","Glasgow"],
    ["Arcadia University - Scottish History","Edinburgh"],
    ["Arcadia University - Scottish Parliamentary Program","Edinburgh"],
    ["Arcadia University - Scottish Universities International Summer School","Edinburgh"],
    ["Arcadia University - SOAS, University of London","London"],
    ["Arcadia University - St Mary's University","London"],
    ["Arcadia University - STEM Summer Research - Aberdeen","Aberdeen"],
    ["Arcadia University - STEM Summer Research - Brisbane","Brisbane"],
    ["Arcadia University - STEM Summer Research - Dublin","Dublin"],
    ["Arcadia University - STEM Summer Research - Glasgow","Glasgow"],
    ["Arcadia University - STEM Summer Research - Kings College London","London"],
    ["Arcadia University - STEM Summer Research - Limerick","Limerick"],
    ["Arcadia University - STEM Summer Research - London","London"],
    ["Arcadia University - Sydney Internship Program","Sydney"],
    ["Arcadia University - Sydney Internship Program Summer","Sydney"],
    ["Arcadia University - Trasimeno Archaeology Field School","Perugia"],
    ["Arcadia University - Trinity College Dublin","Dublin"],
    ["Arcadia University - Umbra Institute","Perugia"],
    ["Arcadia University - Umbra Institute Intensive Italian","Perugia"],
    ["Arcadia University - Umbra Institute Intensive Italian Summer","Perugia"],
    ["Arcadia University - Umbra Institute Summer","Perugia"],
    ["Arcadia University - Universita Degli Studi di Perugia","Perugia"],
    ["Arcadia University - University College Cork","Cork"],
    ["Arcadia University - University College Dublin","Dublin"],
    ["Arcadia University - University College London","London"],
    ["Arcadia University - University College London Summer STEM","London"],
    ["Arcadia University - University of Aberdeen","Aberdeen"],
    ["Arcadia University - University of Auckland","GreatBarrierReef"],
    ["Arcadia University - University of Canterbury","Christchurch"],
    ["Arcadia University - University of Edinburgh","Edinburgh"],
    ["Arcadia University - University of Glasgow","Glasgow"],
    ["Arcadia University - University of Limerick","Limerick"],
    ["Arcadia University - University of Limerick Summer","Limerick"],
    ["Arcadia University - University of Manchester","Manchester"],
    ["Arcadia University - University of Melbourne","Melbourne"],
    ["Arcadia University - University of New South Wales","Sydney"],
    ["Arcadia University - University of Otago","Dunedin"],
    ["Arcadia University - University of Oxford","Oxford"],
    ["Arcadia University - University of Queensland","Brisbane"],
    ["Arcadia University - University of St Andrews","St.Andrews"],
    ["Arcadia University - University of Stirling","Stirling"],
    ["Arcadia University - University of Stirling Summer","Stirling"],
    ["Arcadia University - University of Sydney","Sydney"],
    ["Arcadia University - University of Technology, Sydney","Sydney"],
    ["Arcadia University - University of Westminster","London"],
    ["Arcadia University - University of Winchester","Winchester"],
    ["Arcadia University - University of Wollongong","Sydney"],
    ["Arcadia University - University of York","York"],
    ["Arcadia University - Victoria University of Wellington","Wellington"],
    ["Arcadia University- LSE Summer School","London"],
    ["Australia: Human Impacts on the Natural Environment","Atherton"],
    ["Aviation Summer Program","Bordeaux"],
    ["Balkan Language Initiative","Belgrade"],
    ["Ben Gurion University","BeerSheva "],
    ["Berlin Then and Now: People, Places, Experiences","Berlin"],
    ["Between France and Morocco: Diversity in the Francophone World","Aix-en-Provence"],
    ["Brazil: Alpha Zeta Partners","CampoGrande"],
    ["Castles, Celts and Curries: Multicultural Histories and Legacies of the United Kingdom","Cardiff"],
    ["CET Film Production","Prague"],
    ["Child Family Health International (CFHI) Ecuador","LaPaz"],
    ["Child Family Health International (CFHI) Tanzania","Guayaquil"],
    ["CIEE Art and Sciences Program in Hyderabad, India","Arusha"],
    ["CIEE Middle East Studies in Amman, Jordan","Ancud"],
    ["CIEE Summer Arabic Language Program in Amman, Jordan","Amman"],
    ["CIEE Summer Russian Language Program in St. Petersburg, Russia","Hyderabad"],
    ["CINECU: Hispanic Studies in Multiple Disciplines","Amman"],
    ["Costa Rica: Sustainable Service Learning","Amman"],
    ["Cross Cultural Solutions--Volunteer in Costa Rica for STEP Students, Costa Rica","St.Petersburg"],
    ["Cross Cultural Solutions--Volunteer in Ghana for STEP Students","Seville"],
    ["Cross Cultural Solutions--Volunteer in Thailand for STEP Students","Cahuita"],
    ["CYA (College Year in Athens)","Guanacaste"],
    ["Czech Republic: Sustainability and Agricultural Policy in the EU","VoltaRegion"],
    ["Dance Denmark","Azrou"],
    ["Design Principles and Biomedical Research at Nanjing University","Nan"],
    ["DIS - Study Abroad in Copenhagen, Denmark","Athens"],
    ["DIS - Study Abroad in Stockholm, Sweden","Brno"],
    ["DIS - Summer in Scandinavia","Aalborg"],
    ["DIS Copenhagen - Summer Courses","Beijing"],
    ["DIS Stockholm - Summer Courses","Copenhagen"],
    ["Dresden Summer Language Program","Stockholm"],
    ["Engineering the Castles and Cathedrals of England and Wales","Copenhagen"],
    ["England/Scotland: Agricultural and Environmental Communication","Copenhagen"],
    ["England: Evolution in Darwin's World and Ours","Stockholm"],
    ["European Architecture Studies","Berlin"],
    ["Exploring Jamaican Arts and Culture","Caernarfon"],
    ["FCOB Freshman Global Lab","Bath"],
    ["FCOB Global Business Expedition: Panama","Cambridge"],
    ["FCOB Sustainable Business Global Lab","Basel"],
    ["FCOB: Introduction to Business in Asia Pacific Global Lab","Berlin"],
    ["FIE: Conflict and the Struggle for Peace: Explorations in Ireland and the Middle East Summer Program","Amsterdam"],
    ["Fisher College of Business Undergraduate Exchange - Audencia Business School","Aachen"],
    ["Fisher College of Business Undergraduate Exchange - Copenhagen Business School (CBS)Location: Agra"],
    ["Fisher College of Business Undergraduate Exchange - Curtin University","Kingston"],
    ["Fisher College of Business Undergraduate Exchange - Ecole de Management Strasbourg","Berlin"],
    ["Fisher College of Business Undergraduate Exchange - Erasmus University, Rotterdam School of Management (RSM)","Colon"],
    ["Fisher College of Business Undergraduate Exchange - Hong Kong University of Science and Technology (HKUST)","Almhult"],
    ["Fisher College of Business Undergraduate Exchange - Peking University, Guanghua School of Management","Central"],
    ["Fisher College of Business Undergraduate Exchange - Rikkyo University, College of Business","Amman"],
    ["Fisher College of Business Undergraduate Exchange - Thammasat University","Nantes"],
    ["Fisher College of Business Undergraduate Exchange - Universidad de Chile","Copenhagen"],
    ["Fisher College of Business Undergraduate Exchange - Universidad Pontificia ComillasLocation: Perth"],
    ["Fisher College of Business Undergraduate Exchange - Universita Commerciale Luigi Bocconi","Strasbourg"],
    ["Fisher College of Business Undergraduate Exchange - University of Dublin, Trinity College","Rotterdam"],
    ["Fisher College of Business Undergraduate Exchange - Vienna University of Economics and Business,  Wirtschaftsuniversität Wien (WU)","Kowloon"],
    ["Fisher College of Business Undergraduate Exchange - WHU, Otto Beisheim School of Management","Beijing"],
    ["Genocide and Its Aftermath in Rwanda","Tokyo"],
    ["Global May Bolivia","BrasBasah"],
    ["Global May Great Britain","Bangkok"],
    ["Global May Hungary","Santiago"],
    ["Global May Spain","Madrid"],
    ["Global May Uganda","Milan"],
    ["Goethe-Institut","Dublin"],
    ["Greece - Introduction to Western Tradition and Contemporary Issues in Corfu, GreeceLocation: Vienna"],
    ["GVI--Volunteer in Costa Rica for STEP Students","Vallendar"],
    ["GVI--Volunteer in Fiji for STEP Students","Butare"],
    ["Haifa University","Cochabamba"],
    ["Higher Education in Brazil","Edinburgh"],
    ["Hokkaido University","Balotonfured"],
    ["IAU: Aix-en-Provence, France","Cadiz"],
    ["Iceland: Environment and Natural Resources","Entebbe"],
    ["IES Abroad Nantes - French Language Immersion & Area Studies","Dresden"],
    ["IES Abroad Paris Summer – Language Immersion","Athens"],
    ["IFSA- 21st Century City","Jalova"],
    ["IFSA- Summer in Shanghai","DawasamuDistrict"],
    ["Impact of HIV: Tanzania","Kerala"],
    ["Indonesia: First Education Experience Program (FEEP)","ChiangMai"],
    ["Indonesia: Tourism, Culture and Local Communities","Haifa"],
    ["ISA Barcelona, Spain: Spanish Language & Culture - Summer","Jerusalem"],
    ["ISA Barcelona, Spain: Spanish Language, Liberal Arts & Business- Semester","Cachoeira"],
    ["ISA Buenos Aires, Argentina: Latin American Studies- Semester","Sapporo"],
    ["ISA Granada, Spain: Hispanic Studies- Semester","Aix-en-Provence"],
    ["ISA Granada, Spain: Spanish Language, Culture & Electives - Semester","Borgarnes"],
    ["ISA Heredia, Costa Rica: Spanish Language & Latin American Literature- Summer","Nantes"],
    ["ISA Lima, Peru: Business, Latin American Studies and Spanish Language - Summer","Paris"],
    ["ISA Lima, Peru: Health Science, Field Work & Medical Spanish - Summer","Shanghai"],
    ["ISA Lima, Peru: Liberal Arts with Locals- Academic Year/Semester","Shanghai"],
    ["ISA Paris, France: French Language & Culture at The Sorbonne - Cours de Civilisation Française de la Sorbonne - Semester/Academic Year","DaresSalaam"],
    ["ISA Paris, France: French Language & Liberal Arts at the  Institut Catholique de Paris - Semester/Academic Year","Bali"],
    ["ISA Salamanca, Spain: Spanish Language & Culture - Summer","Bali"],
    ["ISA Seoul, South Korea: Business Courses in English with Locals & Korean Language - Academic Year/Semester","Barcelona"],
    ["ISA Seoul, South Korea: Korean Language & Electives in English at Korea University - Summer","Barcelona"],
    ["ISA Seoul, South Korea: STEM, Social Sciences & Liberal Arts - Semester","BuenosAires"],
    ["ISA Spanish GE Language & Culture Program in Barranquilla, Colombia","BuenosAires"],
    ["ISA Valencia, Spain: Hispanic Studies - Summer","Florianopolis"],
    ["ISA Valparaiso/ Vina del Mar, Chile: Latin American Studies & Courses with Locals- Semester","Granada"],
    ["ISA Valparaiso/ Vina del Mar, Chile: Spanish Language & Latin American Studies - Semester","Granada"],
    ["ISA Valparaiso/ Vina del Mar, Chile: Spanish Language & Latin American Studies - Summer","Heredia"],
    ["Italian Language Program in Lecce, Italy","Lima"],
    ["Italy: International Food Policy - The Italian Approach","Lima"],
    ["Korea University","Lima"],
    ["Linguistics Research in Aix-en-Provence","Paris"],
    ["Literary Locations","Paris"],
    ["London Culture and City","Salamanca"],
    ["Malawi Field Research Methods for Politics","SanJose"],
    ["Moritz College of Law - East China University of Political Science and Law","Seoul"],
    ["Moritz College of Law - Peking University","Seoul"],
    ["Moritz College of Law - Southwest University of Political Science and Law","Seoul"],
    ["Moritz College of Law - University of Passau","Barranquilla"],
    ["Music, Education, and Artistry: The Heart of Europe","Valencia"],
    ["New Zealand: Sustainable Tourism & Human Impacts on the Environment","VinadelMar"],
    ["Nursing Experience in Norway","VinadelMar"],
    ["Pachaysana Institute: Rehearsing Change, Ecuador","VinadelMar"],
    ["Politecnico di Torino","Lecce"],
    ["Pontifícia Universidade Católica do Rio de Janeiro (PUC-Rio)","Bologna"],
    ["Portuguese GE Language and Culture in Curitiba, Brazil","Seoul"],
    ["Psychology and Culture in Europe","Aix-en-Provence"],
    ["Rikkyo University","Rome"],
    ["Sant'Anna Institute Internship Program in Sorrento, Italy","London"],
    ["Scotland's Ruminants","Dedza"],
    ["Semester at Sea - Fall Voyage 2019","Shanghai"],
    ["Semester at Sea - Spring Voyage 2019","Beijing"],
    ["Semester at Sea - Spring Voyage 2020","Chongqing"],
    ["Siena Italian Studies","Passau"],
    ["SIT Study Abroad Madagascar: Traditional Medicine And Health Care Systems","CividaledelFriuli"],
    ["SIT Study Abroad Rwanda: Post-Genocide Restoration and Peacebuilding","Christchurch"],
    ["SIT Study Abroad Senegal: Global Security and Religious Pluralism","Drobak"],
    ["SIT Study Abroad South Africa: Community Health and Social Policy","Quito"],
    ["SIT Study Abroad South Africa: Education and Social Change","Boquete"],
    ["SIT Study Abroad Tanzania: Wildlife Conservation and Political Ecology","Turin"],
    ["SIT Study Abroad Tanzania: Zanzibar Coastal Ecology and Natural Resource ManagementLocation: RiodeJaneiro"],
    ["SIT Study Abroad Uganda/Rwanda: Peace and Conflict in the Lake Victoria Basin","Curitiba"],
    ["SIT Study Abroad Uganda: Development Studies","Bonn"],
    ["Social Issues and Human Rights","Tokyo"],
    ["Social Work in India with a Focus on Health and Mental Health","Sorrento"],
    ["Summer Course in Modern Greek Studies (THYESPA)","Edinburgh"],
    ["Summer French at Laval","Accra"],
    ["Sustainability and Social Justice in Ecuador","Amsterdam"],
    ["Sustainable Resilient Communities - Maji Marwa","Accra"],
    ["Taipei National University of the Arts","Accra"],["The Italian City","Siena"],
    ["The School for Field Studies -  Fundamentals of Marine Conservation","FortDauphin(Tolagnaro)"],
    ["The School for Field Studies -  Marina Megafauna","Antananarivo"],
    ["The School for Field Studies - Carnivores of the African Plains","Gulu"],
    ["The School for Field Studies - Coffee and Chocolate: A Taste of Sustainability","Dakar"],
    ["The School for Field Studies - Forests in the Land of the Thunder Dragon","CapeTown"],
    ["The School for Field Studies - Fundamentals of Sustainability Research","Durban"],
    ["The School for Field Studies - Fundamentals of Wildlife Management","CapeTown"],
    ["The School for Field Studies – Marine Resource Studies","CapeTown"],
    ["The School for Field Studies - Rainforests of New Zealand and Australia","Arusha"],
    ["The School for Field Studies - Sustainable Development Studies","Zanzibar"],
    ["The School for Field Studies – Tropical Island Biodiversity Studies","Gulu"],
    ["The School for Field Studies - Tropical Rainforest Studies","Kampala"],
    ["The School for Field Studies - Watersheds of the Wet Tropics","Chichicastenango"],
    ["The School for Field Studies - Wildlife Management Studies","Bangalore"],
    ["Tohoku University","Arusha"],
    ["Tohoku University (Graduate)","Asan"],
    ["Trinity Laban Conservatoire of Music and Dance","Athens"],
    ["Trondbuss Molecular Genetics","QuebecCity"],
    ["Université de Bourgogne Centre International d'Etudes Françaises (CIEF)","Cuenca"],
    ["Universite de Savoie Mont Blanc","Arusha"],
    ["University of Bedfordshire","Taipei"],
    ["University of Bonn","Athens"],
    ["University of Minnesota: MSID Ecuador","Bologna"],
    ["University of Minnesota: MSID Kenya","SouthCaicos"],
    ["University of Minnesota: MSID Senegal","SouthCaicos"],
    ["University of Minnesota: MSID Thailand","MoyoHillCamp"],
    ["University of Minnesota: Study Abroad in Montpellier","Atenas"],
    ["University of Tsukuba","Jakar"],
    ["Uppsala University","Atenas"],
    ["Why Do We Travel?","MoyoHillCamp"],
    ["Zambia Culture and Society","SouthCaicos"]]

    arr.each do |a|
        if !( geo[a[1]] == "" or geo[a[1]] == nil )
            geoarr <<  [geo[a[1]], ("<h2>"+a[0]+"</h2>")]
        end
    end
    result = "["
    geoarr.each do |g| 
        result += ("[\""+g[0]+"\",\"" + g[1] + "\"],\n" )
    end
    result += "]"
    result.gsub!(/"\(/, "{lat: ")
    result.gsub!(/\)"/, "}")
    puts result.gsub!(/\d,/, ", lng: ")
end
